# Generated by Django 3.2.3 on 2021-05-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='images',
        ),
        migrations.AddField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(to='imageservice.Images'),
        ),
    ]
