# Generated by Django 3.2.3 on 2021-05-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageservice', '0005_alter_album_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
    ]
