# Generated by Django 3.2.3 on 2021-05-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageservice', '0006_alter_album_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
